import { resolveLabelOrKey } from '../utils/label-resolver.js';
import {
  heading,
  inlineCode,
  table,
  lines,
} from '../utils/markdown-helpers.js';

interface LabelEntry {
  language: string;
  label: string;
}

interface Reference {
  key?: string;
  ref?: string;
  domain?: string;
  flow?: string;
  version?: string;
}

interface ExtensionJson {
  key?: string;
  _comment?: string;
  domain?: string;
  flow?: string;
  flowVersion?: string;
  version?: string;
  tags?: string[];
  attributes?: {
    type?: number;
    scope?: number;
    task?: {
      order?: number;
      task?: Reference;
      mapping?: unknown;
    };
    labels?: LabelEntry[];
  };
}

const EXT_TYPE_LABELS: Record<number, string> = {
  1: 'Global',
  2: 'Global And Requested',
  3: 'Defined Flows',
  4: 'Defined Flow And Requested',
};

const EXT_SCOPE_LABELS: Record<number, string> = {
  1: 'Get Instance',
  2: 'Get All Instances',
  3: 'Everywhere',
};

function refDisplay(ref: Reference | undefined | null): string {
  if (!ref) return '-';
  if (ref.ref) return inlineCode(ref.ref);
  return inlineCode(ref.key ?? '?');
}

export function generateExtensionMarkdown(extensionJson: unknown): string {
  const ext = extensionJson as ExtensionJson;
  const attrs = ext.attributes;
  const title = resolveLabelOrKey(attrs?.labels, ext.key ?? 'Extension');

  const sections: (string | null | undefined | false)[] = [];

  sections.push(heading(1, title));

  if (ext._comment) {
    sections.push(ext._comment);
  }

  sections.push(heading(2, 'Metadata'));
  sections.push(
    table(
      ['Property', 'Value'],
      [
        ['Key', inlineCode(ext.key ?? '-')],
        ['Domain', inlineCode(ext.domain ?? '-')],
        ['Version', ext.version ?? '-'],
        ['Type', EXT_TYPE_LABELS[attrs?.type ?? 0] ?? String(attrs?.type ?? '-')],
        ['Scope', EXT_SCOPE_LABELS[attrs?.scope ?? 0] ?? String(attrs?.scope ?? '-')],
        ['Tags', ext.tags?.length ? ext.tags.map((t) => inlineCode(t)).join(', ') : '-'],
      ],
    ),
  );

  if (attrs?.task?.task) {
    sections.push(heading(2, 'Task'));
    sections.push(
      table(
        ['Order', 'Task'],
        [[String(attrs.task.order ?? 1), refDisplay(attrs.task.task)]],
      ),
    );
  }

  sections.push('\n---\n*Generated by vNext Forge*');

  return lines(...sections);
}
