import { resolveLabelOrKey } from '../utils/label-resolver.js';
import {
  heading,
  bold,
  inlineCode,
  table,
  lines,
} from '../utils/markdown-helpers.js';

interface LabelEntry {
  language: string;
  label: string;
}

interface Reference {
  key?: string;
  ref?: string;
  domain?: string;
  flow?: string;
  version?: string;
}

interface TaskExecution {
  _comment?: string;
  order?: number;
  task?: Reference;
}

interface FunctionJson {
  key?: string;
  _comment?: string;
  domain?: string;
  flow?: string;
  flowVersion?: string;
  version?: string;
  tags?: string[];
  attributes?: {
    scope?: string;
    task?: TaskExecution;
    onExecutionTasks?: TaskExecution[];
    output?: unknown;
    labels?: LabelEntry[];
    roles?: { role: string; grant: string }[];
    verbs?: string[];
    inputSchema?: unknown;
    outputSchema?: unknown;
    inputView?: unknown;
    outputView?: unknown;
  };
}

const SCOPE_LABELS: Record<string, string> = {
  D: 'Domain',
  F: 'Flow',
  I: 'Instance',
};

function refDisplay(ref: Reference | undefined | null): string {
  if (!ref) return '-';
  if (ref.ref) return inlineCode(ref.ref);
  return inlineCode(ref.key ?? '?');
}

/**
 * Flattens one contract slot (`inputView` / `outputView` / `inputSchema` /
 * `outputSchema`) into table rows.
 *
 * A slot arrives in one of three wire shapes — a bare reference, an array
 * of rule entries, or a `{views: […]}` / `{schemas: […]}` wrapper. Entries
 * are evaluated in order and the first match wins; an entry without a rule
 * always matches, so it is the fallback.
 *
 * The parsing is duplicated from designer-ui's `functionContractSlots`
 * rather than imported: doc-gen depends only on `vnext-types`, and pulling
 * in a React UI package for this would invert the dependency policy.
 */
function contractSlotRows(
  label: string,
  value: unknown,
  entryKey: 'view' | 'schema',
  wrapperKey: 'views' | 'schemas',
): string[][] {
  if (value == null || typeof value !== 'object') return [];

  const wrapped = (value as Record<string, unknown>)[wrapperKey];
  const entries = Array.isArray(value)
    ? (value as unknown[])
    : Array.isArray(wrapped)
      ? (wrapped as unknown[])
      : null;

  if (!entries) return [[label, 'Always', refDisplay(value as Reference)]];

  return entries.map((raw, index) => {
    const entry = (raw ?? {}) as Record<string, unknown>;
    return [
      label,
      entry.rule ? `Rule #${index + 1}` : 'Fallback',
      refDisplay(entry[entryKey] as Reference | undefined),
    ];
  });
}

export function generateFunctionMarkdown(functionJson: unknown): string {
  const fn = functionJson as FunctionJson;
  const attrs = fn.attributes;
  const title = resolveLabelOrKey(attrs?.labels, fn.key ?? 'Function');

  const sections: (string | null | undefined | false)[] = [];

  sections.push(heading(1, title));

  if (fn._comment) {
    sections.push(fn._comment);
  }

  sections.push(heading(2, 'Metadata'));
  sections.push(
    table(
      ['Property', 'Value'],
      [
        ['Key', inlineCode(fn.key ?? '-')],
        ['Domain', inlineCode(fn.domain ?? '-')],
        ['Version', fn.version ?? '-'],
        ['Scope', SCOPE_LABELS[attrs?.scope ?? ''] ?? attrs?.scope ?? '-'],
        ['Tags', fn.tags?.length ? fn.tags.map((t) => inlineCode(t)).join(', ') : '-'],
      ],
    ),
  );

  const contractRows = [
    ...contractSlotRows('Input Schema', attrs?.inputSchema, 'schema', 'schemas'),
    ...contractSlotRows('Output Schema', attrs?.outputSchema, 'schema', 'schemas'),
    ...contractSlotRows('Input View', attrs?.inputView, 'view', 'views'),
    ...contractSlotRows('Output View', attrs?.outputView, 'view', 'views'),
  ];

  if (attrs?.verbs?.length || contractRows.length) {
    sections.push(heading(2, 'Contract'));
    if (attrs?.verbs?.length) {
      sections.push(`${bold('Verbs')}: ${attrs.verbs.map((verb) => inlineCode(verb)).join(', ')}`);
    }
    if (contractRows.length) {
      sections.push(table(['Contract', 'Selection', 'Reference'], contractRows));
    }
  }

  if (attrs?.task) {
    sections.push(heading(2, 'Task'));
    sections.push(
      table(
        ['Order', 'Task', 'Description'],
        [[String(attrs.task.order ?? 1), refDisplay(attrs.task.task), attrs.task._comment ?? '-']],
      ),
    );
  }

  if (attrs?.onExecutionTasks?.length) {
    sections.push(heading(2, 'Execution Tasks'));
    const rows = attrs.onExecutionTasks.map((t) => [
      String(t.order ?? '-'),
      refDisplay(t.task),
      t._comment ?? '-',
    ]);
    sections.push(table(['Order', 'Task', 'Description'], rows));
  }

  if (attrs?.roles?.length) {
    sections.push(heading(2, 'Roles'));
    const rows = attrs.roles.map((r) => [inlineCode(r.role), r.grant]);
    sections.push(table(['Role', 'Grant'], rows));
  }

  sections.push('\n---\n*Generated by vNext Forge*');

  return lines(...sections);
}
