import { resolveLabelOrKey } from '../utils/label-resolver.js';
import {
  heading,
  bold,
  inlineCode,
  table,
  lines,
} from '../utils/markdown-helpers.js';

interface LabelEntry {
  language: string;
  label: string;
}

interface Reference {
  key?: string;
  ref?: string;
  domain?: string;
  flow?: string;
  version?: string;
}

interface TaskExecution {
  _comment?: string;
  order?: number;
  task?: Reference;
}

interface FunctionJson {
  key?: string;
  _comment?: string;
  domain?: string;
  flow?: string;
  flowVersion?: string;
  version?: string;
  tags?: string[];
  attributes?: {
    scope?: string;
    task?: TaskExecution;
    onExecutionTasks?: TaskExecution[];
    output?: unknown;
    labels?: LabelEntry[];
    roles?: { role: string; grant: string }[];
  };
}

const SCOPE_LABELS: Record<string, string> = {
  D: 'Domain',
  F: 'Flow',
  I: 'Instance',
};

function refDisplay(ref: Reference | undefined | null): string {
  if (!ref) return '-';
  if (ref.ref) return inlineCode(ref.ref);
  return inlineCode(ref.key ?? '?');
}

export function generateFunctionMarkdown(functionJson: unknown): string {
  const fn = functionJson as FunctionJson;
  const attrs = fn.attributes;
  const title = resolveLabelOrKey(attrs?.labels, fn.key ?? 'Function');

  const sections: (string | null | undefined | false)[] = [];

  sections.push(heading(1, title));

  if (fn._comment) {
    sections.push(fn._comment);
  }

  sections.push(heading(2, 'Metadata'));
  sections.push(
    table(
      ['Property', 'Value'],
      [
        ['Key', inlineCode(fn.key ?? '-')],
        ['Domain', inlineCode(fn.domain ?? '-')],
        ['Version', fn.version ?? '-'],
        ['Scope', SCOPE_LABELS[attrs?.scope ?? ''] ?? attrs?.scope ?? '-'],
        ['Tags', fn.tags?.length ? fn.tags.map((t) => inlineCode(t)).join(', ') : '-'],
      ],
    ),
  );

  if (attrs?.task) {
    sections.push(heading(2, 'Task'));
    sections.push(
      table(
        ['Order', 'Task', 'Description'],
        [[String(attrs.task.order ?? 1), refDisplay(attrs.task.task), attrs.task._comment ?? '-']],
      ),
    );
  }

  if (attrs?.onExecutionTasks?.length) {
    sections.push(heading(2, 'Execution Tasks'));
    const rows = attrs.onExecutionTasks.map((t) => [
      String(t.order ?? '-'),
      refDisplay(t.task),
      t._comment ?? '-',
    ]);
    sections.push(table(['Order', 'Task', 'Description'], rows));
  }

  if (attrs?.roles?.length) {
    sections.push(heading(2, 'Roles'));
    const rows = attrs.roles.map((r) => [inlineCode(r.role), r.grant]);
    sections.push(table(['Role', 'Grant'], rows));
  }

  sections.push('\n---\n*Generated by vNext Forge*');

  return lines(...sections);
}
