import { heading, table, inlineCode, lines } from '../utils/markdown-helpers.js';

export interface ComponentDocEntry {
  key: string;
  category: string;
  label: string;
  description?: string;
  relativePath: string;
}

const CATEGORY_ORDER = [
  'workflows',
  'tasks',
  'functions',
  'extensions',
  'schemas',
  'views',
];

function categoryTitle(category: string): string {
  return category.charAt(0).toUpperCase() + category.slice(1);
}

export function generateIndexMarkdown(
  components: ComponentDocEntry[],
  projectName?: string,
): string {
  const sections: (string | null | undefined | false)[] = [];

  sections.push(heading(1, `${projectName ?? 'Project'} - Component Documentation`));
  sections.push(
    'This document provides an index of all vNext components in the project.',
  );

  const grouped = new Map<string, ComponentDocEntry[]>();
  for (const c of components) {
    const list = grouped.get(c.category) ?? [];
    list.push(c);
    grouped.set(c.category, list);
  }

  const sortedCategories = [...grouped.keys()].sort(
    (a, b) =>
      (CATEGORY_ORDER.indexOf(a) === -1 ? 99 : CATEGORY_ORDER.indexOf(a)) -
      (CATEGORY_ORDER.indexOf(b) === -1 ? 99 : CATEGORY_ORDER.indexOf(b)),
  );

  sections.push(heading(2, 'Summary'));
  sections.push(
    table(
      ['Category', 'Count'],
      sortedCategories.map((cat) => [
        categoryTitle(cat),
        String(grouped.get(cat)?.length ?? 0),
      ]),
    ),
  );

  for (const cat of sortedCategories) {
    const items = grouped.get(cat) ?? [];
    sections.push(heading(2, categoryTitle(cat)));

    const rows = items
      .sort((a, b) => a.key.localeCompare(b.key))
      .map((item) => [
        `[${item.label}](${item.relativePath})`,
        inlineCode(item.key),
        item.description ?? '-',
      ]);

    sections.push(table(['Name', 'Key', 'Description'], rows));
  }

  sections.push('\n---\n*Generated by vNext Forge*');

  return lines(...sections);
}
