import { resolveLabelOrKey } from '../utils/label-resolver.js';
import {
  heading,
  inlineCode,
  table,
  lines,
} from '../utils/markdown-helpers.js';

interface LabelEntry {
  language: string;
  label: string;
}

interface SchemaJson {
  key?: string;
  _comment?: string;
  domain?: string;
  flow?: string;
  flowVersion?: string;
  version?: string;
  tags?: string[];
  attributes?: {
    type?: string;
    schema?: {
      $schema?: string;
      $id?: string;
      title?: string;
      description?: string;
      type?: string;
      properties?: Record<string, unknown>;
      required?: string[];
    };
    labels?: LabelEntry[];
  };
}

function propertyRows(
  props: Record<string, unknown>,
  required: string[],
): string[][] {
  return Object.entries(props).map(([name, def]) => {
    const d = def as Record<string, unknown> | undefined;
    const type = d?.oneOf ? 'oneOf' : d?.anyOf ? 'anyOf' : String(d?.type ?? '-');
    const desc = String(d?.description ?? '-');
    const isRequired = required.includes(name) ? 'Yes' : '-';
    return [inlineCode(name), type, desc, isRequired];
  });
}

export function generateSchemaMarkdown(schemaJson: unknown): string {
  const sch = schemaJson as SchemaJson;
  const attrs = sch.attributes;
  const title = resolveLabelOrKey(attrs?.labels, sch.key ?? 'Schema');

  const sections: (string | null | undefined | false)[] = [];

  sections.push(heading(1, title));

  if (sch._comment) {
    sections.push(sch._comment);
  }

  sections.push(heading(2, 'Metadata'));
  sections.push(
    table(
      ['Property', 'Value'],
      [
        ['Key', inlineCode(sch.key ?? '-')],
        ['Domain', inlineCode(sch.domain ?? '-')],
        ['Version', sch.version ?? '-'],
        ['Schema Type', attrs?.type ?? '-'],
        ['Tags', sch.tags?.length ? sch.tags.map((t) => inlineCode(t)).join(', ') : '-'],
      ],
    ),
  );

  const schema = attrs?.schema;
  if (schema) {
    sections.push(heading(2, 'Schema Definition'));
    if (schema.title) sections.push(`**Title:** ${schema.title}`);
    if (schema.description) sections.push(schema.description);
    sections.push(`**Root Type:** ${inlineCode(schema.type ?? 'object')}`);

    if (schema.properties && Object.keys(schema.properties).length) {
      sections.push(heading(3, 'Properties'));
      sections.push(
        table(
          ['Name', 'Type', 'Description', 'Required'],
          propertyRows(schema.properties, schema.required ?? []),
        ),
      );
    }
  }

  sections.push('\n---\n*Generated by vNext Forge*');

  return lines(...sections);
}
