import { resolveLabelOrKey } from '../utils/label-resolver.js';
import {
  heading,
  bold,
  inlineCode,
  table,
  lines,
} from '../utils/markdown-helpers.js';

interface LabelEntry {
  language: string;
  label: string;
}

interface TaskJson {
  key?: string;
  _comment?: string;
  domain?: string;
  flow?: string;
  flowVersion?: string;
  version?: string;
  tags?: string[];
  attributes?: {
    type?: string;
    config?: Record<string, unknown>;
    labels?: LabelEntry[];
  };
}

const TASK_TYPE_LABELS: Record<string, string> = {
  '1': 'Dapr HTTP Endpoint',
  '2': 'Dapr Binding',
  '3': 'Dapr Service',
  '4': 'Dapr PubSub',
  '5': 'Human Task',
  '6': 'HTTP Task',
  '7': 'Script Task',
  '8': 'Condition Task',
  '9': 'Timer Task',
  '10': 'Notification Task',
  '11': 'Start Flow Task',
  '12': 'Trigger Transition Task',
  '13': 'Get Instance Data Task',
  '14': 'SubProcess Task',
  '15': 'Get Instances Task',
};

function configToRows(config: Record<string, unknown>): string[][] {
  return Object.entries(config)
    .filter(([, v]) => v !== null && v !== undefined)
    .map(([k, v]) => {
      const display =
        typeof v === 'object' ? inlineCode(JSON.stringify(v)) : String(v);
      return [inlineCode(k), display];
    });
}

export function generateTaskMarkdown(taskJson: unknown): string {
  const task = taskJson as TaskJson;
  const attrs = task.attributes;
  const title = resolveLabelOrKey(attrs?.labels, task.key ?? 'Task');
  const taskType =
    TASK_TYPE_LABELS[attrs?.type ?? ''] ?? attrs?.type ?? '-';

  const sections: (string | null | undefined | false)[] = [];

  sections.push(heading(1, title));

  if (task._comment) {
    sections.push(task._comment);
  }

  sections.push(heading(2, 'Metadata'));
  sections.push(
    table(
      ['Property', 'Value'],
      [
        ['Key', inlineCode(task.key ?? '-')],
        ['Domain', inlineCode(task.domain ?? '-')],
        ['Version', task.version ?? '-'],
        ['Type', taskType],
        ['Tags', task.tags?.length ? task.tags.map((t) => inlineCode(t)).join(', ') : '-'],
      ],
    ),
  );

  if (attrs?.config && Object.keys(attrs.config).length) {
    sections.push(heading(2, 'Configuration'));
    sections.push(table(['Property', 'Value'], configToRows(attrs.config)));
  }

  sections.push('\n---\n*Generated by vNext Forge*');

  return lines(...sections);
}
