import { resolveLabelOrKey } from '../utils/label-resolver.js';
import {
  heading,
  inlineCode,
  table,
  lines,
} from '../utils/markdown-helpers.js';

interface LabelEntry {
  language: string;
  label: string;
}

interface ViewJson {
  key?: string;
  _comment?: string;
  domain?: string;
  flow?: string;
  flowVersion?: string;
  version?: string;
  tags?: string[];
  attributes?: {
    type?: number;
    content?: unknown;
    display?: string;
    labels?: LabelEntry[];
    _comment?: string;
  };
}

const VIEW_TYPE_LABELS: Record<number, string> = {
  1: 'JSON',
  2: 'HTML',
  3: 'Markdown',
  4: 'Deeplink',
  5: 'HTTP',
  6: 'URN',
};

export function generateViewMarkdown(viewJson: unknown): string {
  const view = viewJson as ViewJson;
  const attrs = view.attributes;
  const title = resolveLabelOrKey(attrs?.labels, view.key ?? 'View');

  const sections: (string | null | undefined | false)[] = [];

  sections.push(heading(1, title));

  const comment = view._comment ?? attrs?._comment;
  if (comment) {
    sections.push(comment);
  }

  sections.push(heading(2, 'Metadata'));
  sections.push(
    table(
      ['Property', 'Value'],
      [
        ['Key', inlineCode(view.key ?? '-')],
        ['Domain', inlineCode(view.domain ?? '-')],
        ['Version', view.version ?? '-'],
        [
          'Content Type',
          VIEW_TYPE_LABELS[attrs?.type ?? 0] ?? String(attrs?.type ?? '-'),
        ],
        ['Display Mode', attrs?.display ?? '-'],
        ['Tags', view.tags?.length ? view.tags.map((t) => inlineCode(t)).join(', ') : '-'],
      ],
    ),
  );

  if (attrs?.content) {
    sections.push(heading(2, 'Content'));
    if (typeof attrs.content === 'string') {
      const lang =
        attrs.type === 2 ? 'html' : attrs.type === 3 ? 'markdown' : 'text';
      sections.push(`\`\`\`${lang}\n${attrs.content}\n\`\`\``);
    } else {
      sections.push(`\`\`\`json\n${JSON.stringify(attrs.content, null, 2)}\n\`\`\``);
    }
  }

  sections.push('\n---\n*Generated by vNext Forge*');

  return lines(...sections);
}
