export enum TaskType {
  DaprHttpEndpoint = 1,
  DaprBinding = 2,
  DaprService = 3,
  DaprPubSub = 4,
  Human = 5,
  Http = 6,
  Script = 7,
  Condition = 8,
  Timer = 9,
  Notification = 10,
  StartTrigger = 11,
  DirectTrigger = 12,
  GetInstanceData = 13,
  SubProcess = 14,
  GetInstances = 15,
}
