// ── File Errors ──────────────────────────────────────────────────────────────

export const FILE_ERRORS = {
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_READ_ERROR: 'FILE_READ_ERROR',
  FILE_WRITE_ERROR: 'FILE_WRITE_ERROR',
  FILE_DELETE_ERROR: 'FILE_DELETE_ERROR',
  FILE_ALREADY_EXISTS: 'FILE_ALREADY_EXISTS',
  FILE_INVALID_PATH: 'FILE_INVALID_PATH',
  FILE_PERMISSION_DENIED: 'FILE_PERMISSION_DENIED',
} as const;

// ── Project Errors ───────────────────────────────────────────────────────────

export const PROJECT_ERRORS = {
  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
  PROJECT_ALREADY_EXISTS: 'PROJECT_ALREADY_EXISTS',
  PROJECT_INVALID_CONFIG: 'PROJECT_INVALID_CONFIG',
  PROJECT_LOAD_ERROR: 'PROJECT_LOAD_ERROR',
  PROJECT_SAVE_ERROR: 'PROJECT_SAVE_ERROR',
} as const;

// ── Workflow Errors ───────────────────────────────────────────────────────────

export const WORKFLOW_ERRORS = {
  WORKFLOW_NOT_FOUND: 'WORKFLOW_NOT_FOUND',
  WORKFLOW_INVALID: 'WORKFLOW_INVALID',
  WORKFLOW_PARSE_ERROR: 'WORKFLOW_PARSE_ERROR',
  WORKFLOW_SAVE_ERROR: 'WORKFLOW_SAVE_ERROR',
  WORKFLOW_VERSION_MISMATCH: 'WORKFLOW_VERSION_MISMATCH',
  WORKFLOW_DUPLICATE_STATE: 'WORKFLOW_DUPLICATE_STATE',
  WORKFLOW_MISSING_INITIAL_STATE: 'WORKFLOW_MISSING_INITIAL_STATE',
  WORKFLOW_UNREACHABLE_STATE: 'WORKFLOW_UNREACHABLE_STATE',
  WORKFLOW_CYCLE_DETECTED: 'WORKFLOW_CYCLE_DETECTED',
  WORKFLOW_INVALID_TRANSITION: 'WORKFLOW_INVALID_TRANSITION',
} as const;

// ── Runtime Errors ────────────────────────────────────────────────────────────

export const RUNTIME_ERRORS = {
  RUNTIME_NOT_AVAILABLE: 'RUNTIME_NOT_AVAILABLE',
  RUNTIME_CONNECTION_FAILED: 'RUNTIME_CONNECTION_FAILED',
  RUNTIME_EXECUTION_FAILED: 'RUNTIME_EXECUTION_FAILED',
  RUNTIME_TIMEOUT: 'RUNTIME_TIMEOUT',
  RUNTIME_INVALID_RESPONSE: 'RUNTIME_INVALID_RESPONSE',
} as const;

// ── Simulation Errors ─────────────────────────────────────────────────────────

export const SIMULATION_ERRORS = {
  SIMULATION_INVALID_INPUT: 'SIMULATION_INVALID_INPUT',
  SIMULATION_STATE_NOT_FOUND: 'SIMULATION_STATE_NOT_FOUND',
  SIMULATION_NO_MATCHING_TRANSITION: 'SIMULATION_NO_MATCHING_TRANSITION',
  SIMULATION_MAX_STEPS_EXCEEDED: 'SIMULATION_MAX_STEPS_EXCEEDED',
} as const;

// ── Git Errors ────────────────────────────────────────────────────────────────

export const GIT_ERRORS = {
  GIT_NOT_INITIALIZED: 'GIT_NOT_INITIALIZED',
  GIT_COMMIT_FAILED: 'GIT_COMMIT_FAILED',
  GIT_PUSH_FAILED: 'GIT_PUSH_FAILED',
  GIT_CONFLICT: 'GIT_CONFLICT',
  GIT_INVALID_REF: 'GIT_INVALID_REF',
} as const;

// ── API / Transport Errors ────────────────────────────────────────────────────

export const API_ERRORS = {
  API_BAD_REQUEST: 'API_BAD_REQUEST',
  API_UNAUTHORIZED: 'API_UNAUTHORIZED',
  API_FORBIDDEN: 'API_FORBIDDEN',
  API_NOT_FOUND: 'API_NOT_FOUND',
  API_CONFLICT: 'API_CONFLICT',
  API_UNPROCESSABLE: 'API_UNPROCESSABLE',
  API_PAYLOAD_TOO_LARGE: 'API_PAYLOAD_TOO_LARGE',
  API_RATE_LIMITED: 'API_RATE_LIMITED',
  API_INTERNAL_ERROR: 'API_INTERNAL_ERROR',
} as const;

// ── Internal / Unknown Errors ─────────────────────────────────────────────────

export const INTERNAL_ERRORS = {
  INTERNAL_UNEXPECTED: 'INTERNAL_UNEXPECTED',
  INTERNAL_NOT_IMPLEMENTED: 'INTERNAL_NOT_IMPLEMENTED',
  INTERNAL_ASSERTION_FAILED: 'INTERNAL_ASSERTION_FAILED',
} as const;

// ── Unified ErrorCode type ────────────────────────────────────────────────────

export const ERROR_CODES = {
  ...FILE_ERRORS,
  ...PROJECT_ERRORS,
  ...WORKFLOW_ERRORS,
  ...RUNTIME_ERRORS,
  ...SIMULATION_ERRORS,
  ...GIT_ERRORS,
  ...API_ERRORS,
  ...INTERNAL_ERRORS,
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
